### ISSUE TITLE
Emulators Request from Github list

### ISSUE THREAD

**Issue by AlexIndiex** [kleidis/Troppical#13]
Hi there, a few weeks ago I made this starred projects' list to keep up with the emulators I personally use, feel free to use it to take a look of what can be added to Troppical (emulators for pico8 and playdate could be ignored)

**GitHub URL**
https://github.com/stars/AlexIndiex/lists/emulators

** Have you confirmed the emulator doesn't have a built-in updater?**
Other than RMG and Ryujinx, I am not aware of others 

** Have you confirmed the emulator is distributed through Github releases?**
Yes but some dont, like project64, the list follows FOS emulators

**Comment by kleidis** [comment]
I'll add more emulators after reworking the UI a bit to habdlr more items better

Thanks!

**Comment by kleidis** [comment]
Added emulators which i thought looked interest from your list , basically I only excluded multi-system-emulators but might add later

![image](https://github.com/kleidis/Troppical/assets/167202775/199cb660-472b-4c45-9b40-60563d15139c)
