### ISSUE TITLE
Possible initial linux implementation

### ISSUE THREAD

**Issue by AlexIndiex** [kleidis/Troppical#14]
Hi there, 
I am been working on a similar project of yours but for linux for the past couple of months.
It's not anything fancy, just a bash shell script.
You can check it out here: https://github.com/AlexIndiex/WaveRiftNoobGuides/blob/main/updater-v2.1.sh
If you would like to start working on a linux implementation of your program, you could dm me on discord to disclose a possible merge since my project use BSD-3 license, my username is alexindie, this merge could help you speed up development, it just needs a gui.

**Comment by kleidis** [comment]
I was thinling about a linux port too, figured flathub would be the preferred way, and it already has many emulators, so would a linux port really be useful?

Nevertheless, if more people want Troppical to be on Linux, I'll definitely talk with you

Again, thanks!

**Comment by AlexIndiex** [comment]
Sometimes flatpaks brake for the smallest of reasons, and some Linux folks prefer the portable way to deal with programs.
Other than that, flatpaks (if not specificed) don't really pull beta/nightly/dev builds, so quite some times you have to download those releases yourself for new fixes, some examples are dolphin and mgba, which dev releases are quite a big leap compared to beta or stable.

These reasons only make it more appealing (at least for me) to use our programs to deal with them instead of something like Emudeck.

Other than these preferences and technicalities, thanks for the attention, I look forward to see this project grow.

**Comment by kleidis** [comment]
Alright then. I'm open to a Linux port but I don't have time to port this app to bash myself anymore

If you or any dev reading this knows Python and Qt feel free to port my app to Linux and I'll add you as a collaborator once you make a working prototype
