### ISSUE TITLE
Search for emulators already installed

### ISSUE THREAD

**Issue by MrArdillo** [kleidis/Troppical#2]
insert the location to install or installed previusly supported emulators

**Comment by kleidis** [comment]
More details please?

It already stores the emulator install status on the windows registry

**Comment by MrArdillo** [comment]
Yes, I have already installed the emulator on a folder. Can I use that installation like a base to later use this program to update?

**Comment by MrArdillo** [comment]
So I only need to insert the exe on my emulators folders and it detects the emulators?

**Comment by kleidis** [comment]
The exe can be anywhere on your pc , it will still detect the emulator folder

**Comment by MrArdillo** [comment]
Ah, okay cool. Thanks and sorry for opening an issue for nothing jaja

**Comment by kleidis** [comment]
Hmmm i did test installing on separate partitions and it worked fine on my end

Can you open regedit and go to HKEYCURRENTUSER/Software/*Emulator Name*

And see what path it is passing

You can also run the py file on a terminal and send the logos
