### ISSUE TITLE
[BUG] Windows 11 & Chrome think the program is a virus

### ISSUE THREAD

**Issue by SiriusVI87** [kleidis/Troppical#3]
**Describe the bug**
Windows 11 & Chrome think the program is a virus. The software cannot be downloaded using Google Chrome and it will be quarantined immediately by WIndows virus protection.

**Comment by kleidis** [comment]
I'm using a chrome based browser (tested on both Brave and thorium) and while the browser itself didint detect it as a virus , Windows defender did, you need to add a exception on defender settings
