### ISSUE TITLE
[BUG] sys has no attribute '_MEIPASS'

### ISSUE THREAD

**Issue by BlurrySquire** [kleidis/Troppical#34]
**Describe the bug**
I attempted to run this on windows via powershell in vs code after cloning the repo. I have installed all the dependencies.

**To Reproduce**
Clone the repo, install the dependencies. Run through vs code's run button in the top right corner (requires python extension).

**Screenshots/Videos**
```
PS D:\Development\Projects\Troppical> & "C:/Program Files/Python312/python.exe" d:/Development/Projects/Troppical/main.py
Failed to get latest GitHub release tag: /bin/bash: line 1: gh: command not found

Traceback (most recent call last):
  File "d:\Development\Projects\Troppical\main.py", line 676, in <module>
    qtui = QtUi()
           ^^^^^^
  File "d:\Development\Projects\Troppical\main.py", line 49, in __init__
    self.ui()  # Init UI
    ^^^^^^^^^
  File "d:\Development\Projects\Troppical\main.py", line 79, in ui
    icon_path = os.path.join(sys._MEIPASS, 'icon.ico')
                             ^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute '_MEIPASS'
PS D:\Development\Projects\Troppical> 
```

**Expected behavior**
The user interface to load and allow me to select emulators.

**Windows version and build**
Windows 10 - 10.0.19045 Build 19045

**Comment by kleidis** [comment]
The current master is broken 

Can you try the refactor branch

**Comment by kleidis** [comment]
The way icons was handheld previously was a bit crappy
Now it should be fine

https://github.com/kleidis/Troppical/pull/32
