### ISSUE TITLE
[Emulator Request] Add support for Torzu

### ISSUE THREAD

**Issue by SilentSparrow02** [kleidis/Troppical#4]
**Emulator Name**
Torzu

**GitHub URL**
https://github.com/litucks/torzu

**Have you confirmed the emulator doesn't have a built-in updater?**
Yes

**Comment by kleidis** [comment]
Torzu doesn't ship releases through GitHub but a random file hosting site so I can see what I can do but it will be later on

**Comment by kleidis** [comment]
https://github.com/kleidis/Troppical/commit/b0e9a8cb9787ce6a966549efb5cfc8e27c3c86dd
