### ISSUE TITLE
[BUG] Torzu installation replaced Sudachi with Torzu

### ISSUE THREAD

**Issue by SilentSparrow02** [kleidis/Troppical#8]
**Describe the bug**
I tried to install Torzu into my emulators directory (which already had the Sudachi folder inside it). After installing I found that Torzu was installed in its own folder, but also had replaced Sudachi in the Sudachi folder.

**To Reproduce**
1. Have Torzu and Sudachi installed in the same parent directory
2. Use Troppical to update Torzu (choosing the parent directory as target location)
3. Sreenshot below

**Screenshots/Videos**
![image](https://github.com/kleidis/Troppical/assets/59610509/ef0ca91e-19d6-4da5-8248-02a6145ca73e)

**Expected behavior**
Torzu shouldn't replace Sudachi in its folder

**Windows version and build**
Windows 11 23H2

**Comment by kleidis** [comment]
It works fine on my end
Sudachi was the first one that was installed as you can see on the screenshots

I installed torzu and it didn't replace anything

![image](https://github.com/kleidis/Troppical/assets/167202775/af7f74ec-cdad-4220-9fb7-53fe6f8d869b)

**Comment by SilentSparrow02** [comment]
Some more details: 
In my case I already had Torzu installed in my emulators folder. After the Troppical update I tried to use it to update Torzu. But since Troppical did not recognize the pre-existing version (the update option was greyed out) I selected the proper directory and pressed install. I thought it would overwrite the existing Torzu version. However it ended up overwriting the Sudachi folder instead.

Sorry if my original issue wasn't clear enough!

**Comment by kleidis** [comment]
Are you using the release v1.1?

**Comment by SilentSparrow02** [comment]
Yes I am using v1.1

I downloaded it from the releases page yesterday (before you removed assets)

**Comment by kleidis** [comment]
Can you try the latest release

**Comment by SilentSparrow02** [comment]
Thanks, I tried it the problem seems to be resolved now!

The only issue with the new version is that I have to disable controlled folder access on Windows every time I use the app 😅. I tried to whitelist it but it's not working since the process is titled "main.exe" rather than "init_troppical.exe". If it was possible to create a workaround that would be great! (Such as making the process name "troppical.exe" so we can whitelist it)
![image](https://github.com/kleidis/Troppical/assets/59610509/43a6775c-7f30-4863-ae35-aa402d1f7265)

Allowlist:
![image](https://github.com/kleidis/Troppical/assets/59610509/3f37b959-ad81-4338-8be7-9a583809b514)

**Comment by kleidis** [comment]
Yeah init_troppical.exe is just a small script that downloads the main file from Github and adds it to APPDATA temp directories, So  I don't see how changing the name from main.exe to troppical.exe would fix this since the main.exe file gets deleted once you close the app

You can open another issue for this tho, I am going to see what I can do
