### ISSUE TITLE
Suggestion: Please don't replace the entire folder contents while updating

### ISSUE THREAD

**Issue by SiriusVI87** [kleidis/Troppical#9]
When updating, all the contents seem to be replaced in the Emulator folder. However, I have a portable setup also utilizing symlinks and Whenever I update with Tropical, all of my custom folders are gone.

It would be better of Tropical would just extgract the updates inside the installed folders, instead of replacing all the files.

Thx!

**Comment by kleidis** [comment]
I just took the easy route here but it shouldn't be too hard to replace the files instead of removing the folder

You have to wait a bit tho, I'm not as free fn

**Comment by kleidis** [comment]
Can you try this build

https://github.com/kleidis/Troppical/actions/runs/9417155411/artifacts/1579092348

**Comment by SiriusVI87** [comment]
> Can you try this latest build?
> 
> To make testing easier install an older version of an emulator and update it

Seems to work, thx!

However, the Software takes very long to start now.

**Comment by kleidis** [comment]
https://github.com/kleidis/Troppical/pull/32/commits/3dc780e6129f96ebc69fba1b197a394524424fd7
